# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-20 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zombieapp', '0009_auto_20160320_0602'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='avg_days',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='player',
            name='avg_kills',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='player',
            name='best_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='best_kills',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='party',
            field=models.IntegerField(default=0),
        ),
    ]
