# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-20 17:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zombieapp', '0010_auto_20160320_1657'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='avg_days',
        ),
        migrations.RemoveField(
            model_name='player',
            name='avg_kills',
        ),
        migrations.RemoveField(
            model_name='player',
            name='best_days',
        ),
        migrations.RemoveField(
            model_name='player',
            name='best_kills',
        ),
        migrations.RemoveField(
            model_name='player',
            name='party',
        ),
    ]
